FROM rust:1.67 as builder

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY . .

RUN cargo build

FROM rust:1.67

WORKDIR /app

COPY --from=builder ./app/target/debug/compiled-app .

CMD [ "./compiled-app" ]
