FROM maven:3.8.5-openjdk-17 as builder

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY /app /app

RUN mvn package

FROM openjdk:17

WORKDIR /app

COPY --from=builder /app/target/*.jar ./app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]