FROM alpine:latest as builder

WORKDIR /app

RUN apk add --no-cache bash

SHELL [ "/bin/bash", "-c" ]

RUN apk add make

RUN apk add cmake

RUN apk add build-base

ONBUILD COPY . .

ONBUILD RUN cmake -B ./build

ONBUILD RUN cmake --build ./build/