FROM python:3.10-alpine

WORKDIR /app

RUN apk add --no-cache bash

SHELL [ "/bin/bash", "-c" ]

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python", "-m", "app"]
