FROM node:14-alpine as builder

WORKDIR /app

COPY ./*.json .

RUN npm install

FROM node:14-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY . .

EXPOSE 3000

CMD ["node", "."]