FROM node:14.17.5-alpine as builder

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY ./*.json .

RUN npm install



FROM node:14.17.5-alpine

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY . .

EXPOSE 3000

CMD ["node", "."]